# Generated by Django 3.1.1 on 2022-12-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pics',
            field=models.FileField(null=True, upload_to='files/', verbose_name='Pics'),
        ),
    ]
