# Generated by Django 3.1.1 on 2022-12-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_pics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pics',
            new_name='img',
        ),
    ]
