# Generated by Django 3.1.1 on 2022-12-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221224_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(null=True, upload_to='media/files/', verbose_name='Pics'),
        ),
    ]
