# Generated by Django 3.1.1 on 2022-12-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20221225_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Newspaper',
        ),
    ]
